static const char ntls_client_2_key_pem_str[] = R"""(-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBG0wawIBAQQgPl4N25CV/RrtOz+M
46uQYiOiQUpY/Mz6llXzmQyu7ZehRANCAASfM+pJSh2ouTxv0ADDxhIOfxINitI3
8oXpsNOUJQOiG63vCFCV85Wa+1RPWnGu5aV+SYRTRcnAmqEvbkxoE3ln
-----END PRIVATE KEY-----

-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBG0wawIBAQQgP0XyHkgVEtVCOAS9
OvEJ28PB1913+1Dl3mfHNK4kTiahRANCAARK5iQeza1b++yslnVZIjZTH1OiAvbN
nQQCadIsAzA9/RYevjtjrM4hQl41fFjGMJUpQGVrOrGvBqjnXcl0WKut
-----END PRIVATE KEY-----

)""";
