static const char ntls_server_2_key_pem_str[] = R"""(-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBG0wawIBAQQgjry2eF3VyOJ7Xqpp
kepFcjMHduQNf/QtnjEWGO7kr/GhRANCAAT1FQRH0gW2H4nH1DQ7PsHJH7xPNNUr
mlM2hKUWs6qSCNK6elcz+RsxBWePuMW33Z+D0VyoCreH3XmeLtqh5VTi
-----END PRIVATE KEY-----

-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBG0wawIBAQQg/rTgcF5BiF7pvFsO
pmE+GVOEfpiiBp8uX9jU/7gJpHyhRANCAAQMLC7ADwsLe5uXC7GKctMMRRfQtvVR
4wJt2yJZ5/BUGhoUd800tWtEKsEogtRCbOXTirURkRzKUHfnmQIa7dIL
-----END PRIVATE KEY-----

)""";
